### ISSUE TITLE
Finish the exercise!

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/e-s1-evaluacion-intermedia-garcaplay#1]
Awesome work @garcaplay. Great clean exercise with good HTML semantics and a super cool solution for the page logo.

Here you have some tips to improve it:

- [x] Remove unused files and references
- [x] Use `H1` heading tag for the main title
- [x] We can use CSS to separate words in different lines instead of `BR` tags
- [x] Let's use English for our class selector names
- [x] Block elements don't need to have their width set up to 100% nor 100vw
- [x] The `.main` element should be a SECTION
- [x] The main section height should fit the browser window one
- [x] Page logo should be clickable too

Once you have those fixed how about some extra work? let's add a simple footer to the page with these requirements in mind:
- [x] Copy: `@ 2018 Adalab.`
- [x] Footer background color: #fff
- [x] Footer text color: #585859
- [x] Text should be separated from the footer container by 15px when in mobile devices or with small screens, and by 30px from 768px and up
- [x] In mobile devices (or small screens) the footer text should be centered, otherwise it should be aligned to the left
- [x] BONUS: while there are enough space both MAIN and footer should fit the total browser height

Let me know if you have any doubts ;)

**Comment by garcaplay** [comment]
Done!
